services:
  db:
    container_name: emailStorageDB
    image: postgres:latest
    environment:
      POSTGRES_USER: andrea
      POSTGRES_PASSWORD: italiano
      PGDATA: /data/emailStorageDB
      POSTGRES_DB: emailStorageDB
    volumes:
      - db:/data/postgres
    ports:
      - "5447:5432"
    restart: unless-stopped
    networks:
      - emailStorage-network


volumes:
  db:

networks:
  emailStorage-network:
    driver: bridge
